version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pms-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: pms-frontend
    ports:
      - "3000:3000"
    working_dir: /ui
    command: ["npm", "start"]
    volumes:
      - ./ui:/ui
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend 